# Generated by Django 5.1.6 on 2025-04-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('car_for_sale', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('parts_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('salesperson_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('service_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_ticket_number', models.CharField(max_length=50)),
                ('date_received', models.DateField()),
                ('comments', models.TextField()),
                ('date_returned', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMechanic',
            fields=[
                ('servicemechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.service')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsed',
            fields=[
                ('parts_used_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_used', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.parts')),
                ('service_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_app.serviceticket')),
            ],
        ),
    ]
